"""Initial Migration

Revision ID: 04f7567d9eaf
Revises: 
Create Date: 2026-04-08 10:36:10.979193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f7567d9eaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordens_servico', 'solicitante',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('ordens_servico', 'equipamento_retirado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_ordens_servico_numero_os'), table_name='ordens_servico')
    op.create_index(op.f('ix_ordens_servico_numero_os'), 'ordens_servico', ['numero_os'], unique=False)
    op.drop_column('ordens_servico', 'data_hora_inicio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_servico', sa.Column('data_hora_inicio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ordens_servico_numero_os'), table_name='ordens_servico')
    op.create_index(op.f('ix_ordens_servico_numero_os'), 'ordens_servico', ['numero_os'], unique=True)
    op.alter_column('ordens_servico', 'equipamento_retirado',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'solicitante',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
